CREATE DATABASE "clingen"
  WITH OWNER "postgres"
  ENCODING 'UTF8';

CREATE TABLE clingen_variants (
    ID  SERIAL PRIMARY KEY, 
    GENE_SYMBOL  VARCHAR(20),
    HGNC_ID  VARCHAR(5),
    DISEASE_LABEL TEXT,
    MONDO_DISEASE_ID VARCHAR(7),
    MOI VARCHAR(20),
    SOP VARCHAR(4),
    CLASSIFICATION VARCHAR(20),
    ONLINE_REPORT TEXT,
    CLASSIFICATION_DATE TIMESTAMPTZ,
    GCEP TEXT
);

