
from cmath import nan
import pandas as pd
import numpy as np

str2='''
Clinical Annotation ID	Genotype/Allele	Annotation Text	Allele Function
981755803	AA	Patients with the rs75527207 AA genotype (two copies of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.	
981755803	AG	Patients with the rs75527207 AG genotype (one copy of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.	
981755803	GG	Patients with the rs75527207 GG genotype (do not have a copy of the CFTR G551D variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.	
1449311190	CC	Patients with the CC genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.	
1449311190	CT	Patients with the CT genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need a decreased dose of mercaptopurine, or methotrexate, as compared to children with the TT genotype. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.	
1449311190	TT	Patients with the TT genotype and Precursor Cell Lymphoblastic Leukemia-Lymphoma may need an increased dose of mercaptopurine, or methotrexate, as compared to children with the CC or CT genotypes. Other clinical and genetic factors may also influence dose of mercaptopurine or methotrexate in children with Precursor Cell Lymphoblastic Leukemia-Lymphoma.	
981204774	AA	Patients with AA genotype may have an increased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AG and GG genotype. However, contradictory findings reporting the opposite association for this genotype with decreased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.	
981204774	AG	Patients with AG genotype may have a decreased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AA genotype. However, contradictory findings reporting the opposite association for this genotype with increased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.	
981204774	GG	Patients with GG genotype may have a decreased likelihood of smoking cessation when treated with nicotine replacement therapy (transdermal nicotine patch) as compared to patients with the AA genotype. However, contradictory findings reporting the opposite association for this genotype with increased likelihood of smoking cessation have been published. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation. Other genetic and clinical factors may influence a patient's likelihood of smoking cessation.	
1449191690	CC	Patients with the CC genotype (do not have a copy of the CFTR S977F variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.	
1449191690	CT	Patients with the CT genotype (one copy of the CFTR S977F variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.	
1449191690	TT	Patients with the TT genotype (two copies of the CFTR S977F variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including S977F. Other genetic and clinical factors may also influence response to ivacaftor.	
1449191746	AA	Patients with the AA genotype (two copies of the CFTR R1070Q variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.	
1449191746	AG	Patients with the AG genotype (one copy of the CFTR R1070Q variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.	
1449191746	GG	Patients with the GG genotype (do not have a copy of the CFTR R1070Q variant) and cystic fibrosis have an unknown response to ivacaftor treatment, as response may depend on the presence of other CFTR variants. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including R1070Q. Other genetic and clinical factors may also influence response to ivacaftor.	
981419532	CC	Patients with the CC genotype may have decreased risk of statin-related muscle symptoms as compared to patients with genotype GG or CG. Other genetic and clinical factors may also influence a patient's risk of toxicity.	
981419532	CG	Patients with the CG genotype may have increased risk of statin-related muscle symptoms as compared to patients with genotype CC. Other genetic and clinical factors may also influence a patient's risk of toxicity.	
981419532	GG	Patients with the GG genotype may have increased risk of statin-related muscle symptoms as compared to patients with genotype CC. Other genetic and clinical factors may also influence a patient's risk of toxicity.	
1449566379	AA	Patients with the AA genotype and hypertension may have an increased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.	
1449566379	AG	Patients with the AG genotype and hypertension may have an increased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the GG genotype, but a decreased response as compared to patients with the AA genotype. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.	
1449566379	GG	Patients with the GG genotype and hypertension may have a decreased response to hydrochlorothiazide treatment, as measured by decreases in systolic and diastolic blood pressure, as compared to patients with the AA or AG genotypes. Other genetic and clinical factors may also affect a patient's response to hydrochlorothiazide.	
981419266	*15:02:01	Patients with one or two copies of the HLA-B*15:02:01 allele may have an increased risk of Severe Cutaneous Adverse Reactions, such as Stevens-Johnson Syndrome and Toxic Epidermal Necrolysis, when treated with phenytoin as compared to patients with no HLA-B*15:02:01 alleles or negative for the HLA-B*15:02:01 test. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk of phenytoin-induced adverse reactions.	Presence
1451259580	*1	The CYP2D6*1 allele is assigned as a normal function allele by CPIC. Patients carrying the CYP2D6*1 allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	Normal function
1451259580	*1xN	The CYP2D6*1xN alleles (*1x2 and *1x≥3) have been assigned as increased function alleles by CPIC. Patients carrying the CYP2D6*1xN allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	Increased function
1451259580	*2	The CYP2D6*2 allele is assigned as a normal function allele by CPIC. Patients carrying the CYP2D6*2 allele in combination with alleles that result in a normal metabolizer phenotype who are treated with amitriptyline may have decreased likelihood of side effects as compared to patients with a combination of alleles that result in intermediate or poor metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	Normal function
1451259580	*3	The CYP2D6*3 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*3 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	No function
1451259580	*4	The CYP2D6*4 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*4 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	No function
1451259580	*5	The CYP2D6*5 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*5 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	No function
1451259580	*6	The CYP2D6*6 allele is assigned as a no function allele by CPIC. Patients carrying the CYP2D6*6 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	No function
1451259580	*10	The CYP2D6*10 allele is assigned as a decreased function allele with an activity value of 0.25 by CPIC. Patients carrying the CYP2D6*10 allele in combination with with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	Decreased function (AV 0.25)
1451259580	*41	The CYP2D6*41 allele is assigned as a decreased function allele with an activity value of 0.5 by CPIC. Patients carrying the CYP2D6*41 allele in combination with alleles that result in intermediate or poor metabolizer phenotype who are treated with amitriptyline may have increased likelihood of side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to amitriptyline.	Decreased function
1451265560	*1	The CYP2D6*1 allele is assigned as a normal function allele by CPIC. Patients carrying the *1 allele in combination with alleles that result in a normal metabolizer phenotype may have decreased imipramine dose requirements as compared to patients carrying two increased function alleles or an increased function allele in combination with a normal function allele or a decreased function allele with an activity value of 0.5. Patients carrying the *1 allele in combination with alleles that result in a normal metabolizer phenotype may also have decreased imipramine dose requirements as compared to patients carrying an increased function allele with an activity value of 3 or greater in combination with a no function allele or a decreased function allele with an activity value of 0.25 but increased imipramine dose requirements as compared to patients with a no function allele in combination with a decreased or normal function allele or two decreased or no function alleles. Other genetic and clinical factors may also influence imipramine dose requirements.	Normal function
1451265560	*1xN	The CYP2D6*1xN alleles (*1x2 and *1x≥3) have been assigned as increased function alleles by CPIC. Patients carrying a *1xN allele in combination with a normal or increased function allele or a decreased function allele with an activity value of 0.5 may have increased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype. Patients carrying a *1xN allele with an activity value of 3 or greater in combination with a decreased function allele with an activity value of 0.25 or a no function allele may also have increased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype, while patients carrying a *1xN allele with an activity value of 2 in combination with a decreased function allele with an activity value of 0.25 or a no function allele may have similar imipramine dose requirements as compared to patients with other alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence imipramine dose requirements.	Increased function
1451265560	*2xN	The CYP2D6*2xN alleles (*2x2 and *2x≥3) have been assigned as increased function alleles by CPIC. Patients carrying a *2xN allele in combination with a normal or increased function allele or a decreased function allele with an activity value of 0.5 may have increased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype. Patients carrying a *2xN allele with an activity value of 3 or greater in combination with a decreased function allele with an activity value of 0.25 or a no function allele may also have increased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype, while patients carrying a *2xN allele with an activity value of 2 in combination with a decreased function allele with an activity value of 0.25 or a no function allele may have similar imipramine dose requirements as compared to patients with other alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence imipramine dose requirements.	Increased function
1451265560	*4	The CYP2D6*4 allele is assigned as a no function allele by CPIC. Patients carrying the *4 allele in combination with a normal, decreased or no function allele may have decreased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype, while patients carrying the *4 allele in combination with an increased function allele with an activity value of 3 or greater may have increased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype. Patients carrying the *4 allele in combination with an increased function allele with an activity score of 2 may have similar imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence imipramine dose requirements.	No function
1451265560	*5	The CYP2D6*5 allele is assigned as a no function allele by CPIC. Patients carrying the *5 allele in combination with a normal, decreased or no function allele may have decreased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype, while patients carrying the *5 allele in combination with an increased function allele with an activity value of 3 or greater may have increased imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype. Patients carrying the *5 allele in combination with an increased function allele with an activity score of 2 may have similar imipramine dose requirements as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence imipramine dose requirements.	No function
1451288200	*1	The CYP2D6*1 allele is assigned as a normal function allele by CPIC. Patients carrying the *1 allele in combination with alleles that result in a normal metabolizer phenotype may have decreased risk of toxicity when treated with codeine as compared to patients carrying two increased function alleles or an increased function allele in combination with a normal function allele or a decreased function allele with an activity value of 0.5. Patients carrying the *1 allele in combination with alleles that result in a normal metabolizer phenotype may also have decreased risk of toxicity when treated with codeine as compared to patients carrying an increased function allele with an activity value of 3 or greater in combination with a no function allele or a decreased function allele with an activity value of 0.25 but a similar risk of toxicity when treated with codeine as compared to patients with a no function allele in combination with a decreased or normal function allele or two decreased or no function alleles. Other genetic and clinical factors may also influence risk of codeine toxicity.	Normal function
1451288200	*1xN	The CYP2D6*1xN alleles (*1x2 and *1x≥3) are assigned as increased function alleles by CPIC. Patients carrying a *1xN allele with an activity value of 3 or greater in combination with a normal, increased, decreased or no function allele may have an increased risk of toxicity when treated with codeine as compared to patients with alleles that result in a normal metabolizer phenotype. Patients carrying a *1xN allele with an activity value of 2 in combination with an increased or normal function allele or a decreased function allele with an activity value of 0.5 may also have an increased risk of toxicity when treated with codeine as compared to patients with alleles that result in a normal metabolizer phenotype, while patients carrying a *1xN allele with an activity value of 2 in combination with a no function allele or a decreased function allele with an activity value of 0.25 may have a similar risk of toxicity when treated with codeine as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence risk of codeine toxicity.	Increased function
1451288200	*2	The CYP2D6*2 allele is assigned as a normal function allele by CPIC. Patients carrying the *2 allele in combination with alleles that result in a normal metabolizer phenotype may have decreased risk of toxicity when treated with codeine as compared to patients carrying two increased function alleles or an increased function allele in combination with a normal function allele or a decreased function allele with an activity value of 0.5. Patients carrying the *2 allele in combination with alleles that result in a normal metabolizer phenotype may also have decreased risk of toxicity when treated with codeine as compared to patients carrying an increased function allele with an activity value of 3 or greater in combination with a no function allele or a decreased function allele with an activity value of 0.25 but a similar risk of toxicity when treated with codeine as compared to patients with a no function allele in combination with a decreased or normal function allele or two decreased or no function alleles. Other genetic and clinical factors may also influence risk of codeine toxicity.	Normal function
1451288200	*2xN	The CYP2D6*2xN alleles (*2x2 and *2x≥3) are assigned as increased function alleles by CPIC. Patients carrying a *2xN allele with an activity value of 3 or greater in combination with a normal, increased, decreased or no function allele may have an increased risk of toxicity when treated with codeine as compared to patients with alleles that result in a normal metabolizer phenotype. Patients carrying a *2xN allele with an activity value of 2 in combination with an increased or normal function allele or a decreased function allele with an activity value of 0.5 may also have an increased risk of toxicity when treated with codeine as compared to patients with alleles that result in a normal metabolizer phenotype, while patients carrying a *2xN allele with an activity value of 2 in combination with a no function allele or a decreased function allele with an activity value of 0.25 may have a similar risk of toxicity when treated with codeine as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence risk of codeine toxicity.	Increased function
1451282240	*1	The CYP2D6*1 allele is assigned as a normal function allele by CPIC. Patients carrying the *1 allele in combination with alleles that result in a normal metabolizer phenotype who are treated with atomoxetine may have a decreased, but not absent, risk for treatment related side effects as compared to patients with two no function alleles. Other genetic and clinical factors may also influence response to atomoxetine.	Normal function
1451282240	*3	The CYP2D6*3 allele is assigned as a no function allele by CPIC. Patients carrying the *3 allele in combination with another no function allele who are treated with atomoxetine may have an increased risk for treatment related side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to atomoxetine.	No function
1451282240	*4	The CYP2D6*4 allele is assigned as a no function allele by CPIC. Patients carrying the *4 allele in combination with another no function allele who are treated with atomoxetine may have an increased risk for treatment related side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to atomoxetine.	No function
1451282240	*4xN	The CYP2D6*4xN allele (*4x2) is assigned as a no function allele by CPIC. Patients carrying the *4xN allele in combination with another no function allele who are treated with atomoxetine may have an increased risk for treatment related side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to atomoxetine.	No function
1451282240	*5	The CYP2D^*5 allele is assigned as a no function allele by CPIC. Patients carrying the *5 allele in combination with another no function allele who are treated with atomoxetine may have an increased risk for treatment related side effects as compared to patients with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to atomoxetine.	No function
1451282240	*6	The CYP2D6*6 allele is assigned as a no function allele by CPIC. Patients carrying the *6 allele in combination with another no function allele who are treated with atomoxetine may have an increased risk for treatment related side effects as compared to patients with with alleles that result in a normal metabolizer phenotype. Other genetic and clinical factors may also influence response to atomoxetine.	No function
1451285240	*1	The CYP2D6*1 allele is assigned as a normal function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*1 allele in combination with alleles that result in a normal metabolizer phenotype may have decreased likelihood of recurrence and increased event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with a no function allele in combination with a decreased or normal function allele or two no or decreased function alleles. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	Normal function
1451285240	*2	The CYP2D6*2 allele is assigned as a normal function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*2 allele in combination with alleles that result in a normal metabolizer phenotype may have decreased likelihood of recurrence and increased event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with a no function allele in combination with a decreased or normal function allele or two no or decreased function alleles. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	Normal function
1451285240	*3	The CYP2D6*3 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*3 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*4	The CYP2D6*4 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*4 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*5	The CYP2D6*5 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*5 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*6	The CYP2D6*6 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*6 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*7	The CYP2D6*7 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*7 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*9	The CYP2D6*9 allele is assigned as a decreased function allele with an activity value of 0.5 by CPIC. Patients with breast cancer and carrying the CYP2D6*9 allele in combination with a no or decreased function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	Decreased function
1451285240	*10	The CYP2D6*10 allele is assigned as a decreased function allele with an activity value of 0.25 by CPIC. Patients with breast cancer and carrying the CYP2D6*10 allele in combination with a no or decreased function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	Decreased function (AV 0.25)
1451285240	*10x2	The CYP2D6*10x2 allele is assigned as a decreased function allele with an activity value of 0.5 by CPIC. Patients with breast cancer and carrying the CYP2D6*10x2 allele in combination with a no or decreased function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	Decreased function
1451285240	*11	The CYP2D6*11 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*11 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*17	The CYP2D6*17 allele is assigned as a decreased function allele with an activity value of 0.5 by CPIC. Patients with breast cancer and carrying the CYP2D6*17 allele in combination with a no or decreased function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	Decreased function
1451285240	*21	The CYP2D6*21 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*21 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*36	The CYP2D6*36 allele is assigned as a no function allele by CPIC. Patients with breast cancer and carrying the CYP2D6*36 allele in combination with a no, decreased or normal function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	No function
1451285240	*41	The CYP2D6*41 allele is assigned as a decreased function allele with an activity value of 0.5 by CPIC. Patients with breast cancer and carrying the CYP2D6*41 allele in combination with a no or decreased function allele may have increased likelihood of recurrence and lower event-free and recurrence-free survival when treated with tamoxifen in an adjuvant setting as compared to patients with alleles that result in a normal metabolizer phenotype. However, conflicting evidence has been reported. Be aware that the DPWG guideline for tamoxifen and CYP2D6 has a 'no recommendation' for CYP2D6 ultrarapid metabolizers. Other genetic and clinical factors may also influence response to tamoxifen treatment.	Decreased function
1451226160	AA	Infants who have been exposed to methadone in utero and who have the rs4680 AA genotype may have an increased severity of neonatal abstinence syndrome as compared to infants with the AG or GG genotypes. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226160	AG	Infants who have been exposed to methadone in utero and who have the rs4680 AG genotype may have a decreased severity of neonatal abstinence syndrome as compared to infants with the AA genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226160	GG	Infants who have been exposed to methadone in utero and who have the rs4680 GG genotype may have a decreased severity of neonatal abstinence syndrome as compared to infants with the AA genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226166	AA	Infants who have been exposed to methadone in utero and who are born to women with the AA genotype may be more likely to require treatment with at least two medications for neonatal abstinence syndrome as compared to infants born to women with the AG or GG genotypes. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226166	AG	Infants who have been exposed to methadone in utero and who are born to women with the AG genotype may be less likely to require treatment with at least two medications for neonatal abstinence syndrome as compared to infants born to women with the AA genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226166	GG	Infants who have been exposed to methadone in utero and who are born to women with the GG genotype may be less likely to require treatment with at least two medications for neonatal abstinence syndrome as compared to infants born to women with the AA genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226200	AA	Infants who have been exposed to buprenorphine in utero and who have the AA genotype may be more likely to require medication to treat neonatal abstinence syndrome as compared to infants with the CC genotype. However, this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226200	AC	Infants who have been exposed to buprenorphine in utero and who have the AC genotype may be more likely to require medication to treat neonatal abstinence syndrome as compared to infants with the CC genotype. However, this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226200	CC	Infants who have been exposed to buprenorphine in utero and who have the CC genotype may be less likely to require medication to treat neonatal abstinence syndrome as compared to infants with the AA or AC genotypes. However, this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226206	AA	Infants who have been exposed to methadone in utero and who have the AA genotype may be more likely to require medication to treat neonatal abstinence syndrome as compared to infants with the CC genotype. However, this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226206	AC	Infants who have been exposed to methadone in utero and who have the AC genotype may be more likely to require medication to treat neonatal abstinence syndrome as compared to infants with the CC genotype. However, this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226206	CC	Infants who have been exposed to methadone in utero and who have the CC genotype may be less likely to require medication to treat neonatal abstinence syndrome as compared to infants with the AA or AC genotypes. However, this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226212	AA	Infants who have been exposed to buprenorphine in utero and who are born to women with the rs740603 AA genotype may be less likely to require medication to treat neonatal abstinence syndrome as compared to infants born to women with the GG genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226212	AG	Infants who have been exposed to buprenorphine in utero and who are born to women with the rs740603 AG genotype may be less likely to require medication to treat neonatal abstinence syndrome as compared to infants born to women with the GG genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226212	GG	Infants who have been exposed to buprenorphine in utero and who are born to women with the rs740603 GG genotype may be more likely to require medication to treat neonatal abstinence syndrome as compared to infants born to women with the AA or AG genotypes. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226220	AA	Infants who have been exposed to methadone in utero and who are born to women with the AA genotype may be less likely to require medication to treat neonatal abstinence syndrome as compared to infants born to women with the GG genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226220	AG	Infants who have been exposed to methadone in utero and who are born to women with the AG genotype may be less likely to require medication to treat neonatal abstinence syndrome as compared to infants born to women with the GG genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451226220	GG	Infants who have been exposed to methadone in utero and who are born to women with the GG genotype may be more likely to require medication to treat neonatal abstinence syndrome as compared to infants born to women with the AA or AG genotypes. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451340300	*1	Patients carrying the UGT1A3*1 allele in combination with a normal function allele may have increased exposure of telmisartan as compared to patients with one or more copies of the UGT1A3*2 or *3 allele. Other genetic and clinical factors may also influence metabolism of telmisartan. This annotation only covers the pharmacokinetic relationship between UGT1A3 and telmisartan and does not include evidence about clinical outcomes.	
1451340300	*2	Patients carrying the UGT1A3*2 allele in combination with a UGT1A3*1 or a UGT1A3*2 allele may have decreased exposure of telmisartan as compared to patients with with two normal function alleles. Other genetic and clinical factors may also influence metabolism of telmisartan. This annotation only covers the pharmacokinetic relationship between UGT1A3 and telmisartan and does not include evidence about clinical outcomes.	
1451340300	*3	Patients carrying the UGT1A3*3 allele in combination with a UGT1A3*1 or a UGT1A3*3 allele may have decreased exposure of telmisartan as compared to patients with with two normal function alleles. Other genetic and clinical factors may also influence metabolism of telmisartan. This annotation only covers the pharmacokinetic relationship between UGT1A3 and telmisartan and does not include evidence about clinical outcomes.	
1451340320	CC	Patients with the CC genotype may have increased concentrations of telmisartan as compared to patients with the GG genotype. Other genetic and clinical factors may also influence metabolism of telmisartan. This annotation only covers the pharmacokinetic relationship between SLCO1B3 and telmisartan and does not include evidence about clinical outcomes.	
1451340320	CG	Patients with the CG genotype may have increased concentrations of telmisartan as compared to patients with the GG genotype. Other genetic and clinical factors may also influence metabolism of telmisartan. This annotation only covers the pharmacokinetic relationship between SLCO1B3 and telmisartan and does not include evidence about clinical outcomes.	
1451340320	GG	Patients with the GG genotype may have decreased concentrations of telmisartan as compared to patients with the CC or CG genotype. Other genetic and clinical factors may also influence metabolism of telmisartan. This annotation only covers the pharmacokinetic relationship between SLCO1B3 and telmisartan and does not include evidence about clinical outcomes.	
1450930839	AA	Patients with the AA genotype may have decreased severity of nicotine dependence, as measured by FTND score, as compared to patients with the GG genotype. Other genetic and clinical factors may also affect severity of nicotine dependence.	
1450930839	AG	Patients with the AG genotype may have decreased severity of nicotine dependence, as measured by FTND score, as compared to patients with the GG genotype. Other genetic and clinical factors may also affect severity of nicotine dependence.	
1450930839	GG	Patients with the GG genotype may have increased severity of nicotine dependence, as measured by FTND score, as compared to patients with the AA or AG genotypes. Other genetic and clinical factors may also affect severity of nicotine dependence.	
1451356840	CC	Patients with the rs696 CC genotype may require decreased doses of sufentanil as compared to patients with the TT genotype. Other genetic and clinical factors may also influence sufentanil dosage requirements.	
1451356840	CT	Patients with the rs696 CT genotype may require decreased doses of sufentanil as compared to patients with the TT genotype. Other genetic and clinical factors may also influence sufentanil dosage requirements.	
1451356840	TT	Patients with the rs696 TT genotype may require increased doses of sufentanil as compared to patients with the CC or CT genotypes. Other genetic and clinical factors may also influence sufentanil dosage requirements.	
1451225360	AA	Infants who have been exposed to buprenorphine in utero and who have the rs4680 AA genotype may have an increased severity of neonatal abstinence syndrome as compared to infants with the AG or GG genotypes. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451225360	AG	Infants who have been exposed to buprenorphine in utero and who have the rs4680 AG genotype may have a decreased severity of neonatal abstinence syndrome as compared to infants with the AA genotype. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451225360	GG	Infants who have been exposed to buprenorphine in utero and who have the rs4680 GG genotype may have a decreased severity of neonatal abstinence syndrome as compared to infants with the AA genotype. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1450930464	CC	Patients with the CC genotype may begin using heroin at a later age as compared to patients with the TT genotype. Other genetic and clinical factors may also affect a patient's age at first use of heroin.	
1450930464	CT	Patients with the CT genotype may begin using heroin at a later age as compared to patients with the TT genotype. Other genetic and clinical factors may also affect a patient's age at first use of heroin.	
1450930464	TT	Patients with the TT genotype may begin using heroin at an earlier age as compared to patients with the CC or CT genotypes. Other genetic and clinical factors may also affect a patient's age at first use of heroin.	
1451290960	CC	Patients with diabetes mellitus and the CC genotype who are taking gliclazide may have decreased response as compared to patients with the TT genotype. Other clinical and genetic factors may also influence response to gliclazide in patients with diabetes mellitus.	
1451290960	CT	Patients with diabetes mellitus and the CT genotype who are taking gliclazide may have improved response as compared to patients with the CC genotype and decreased response compared to the TT genotype. Other clinical and genetic factors may also influence response to gliclazide in patients with diabetes mellitus.	
1451290960	TT	Patients with diabetes mellitus and the TT genotype who are taking gliclazide may have improved response as compared to patients with the CC genotype. Other clinical and genetic factors may also influence response to gliclazide in patients with diabetes mellitus.	
1451356520	CC	Patients with the CC genotype may have decreased lipid-lowering response to simvastatin as compared to patients with the TT genotype. However, conflicting evidence has been reported. The effect size may be small. Other genetic and clinical factors may also influence response to simvastatin.	
1451356520	CT	Patients with the CT genotype may have decreased lipid-lowering response to simvastatin as compared to patients with the TT genotype. However, conflicting evidence has been reported. The effect size may be small. Other genetic and clinical factors may also influence response to simvastatin.	
1451356520	TT	Patients with the TT genotype may have increased lipid-lowering response to simvastatin as compared to patients with the CC or CT genotype. However, conflicting evidence has been reported. The effect size may be small. Other genetic and clinical factors may also influence response to simvastatin.	
655386913	*1	Patients carrying the CYP2C19*1 allele in combination with a normal allele and cardiovascular disease who are treated with clopidogrel may have a decreased, but not absent, risk for bleeding events as compared to patients with two increased function alleles or the combination of a normal and increased function allele. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk for bleeding events.	Normal function
655386913	*17	Patients carrying the CYP2C19*17 allele in combination with a normal or increased function allele and cardiovascular disease who are treated with clopidogrel may have an increased risk for bleeding events as compared to patients with two normal function alleles. However, conflicting evidence has been reported. Other genetic and clinical factors may also influence risk for bleeding events.	Increased function
1451356180	CC	Patients with schizophrenia and the rs28379954 CC genotype may have increased serum concentrations of clozapine as compared to patients with the CT genotype. This annotation only covers the pharmacokinetic relationship between rs28379954 and clozapine and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence serum concentrations of clozapine.	
1451356180	CT	Patients with schizophrenia and the rs28379954 CT genotype may have decreased serum concentrations of clozapine as compared to patients with the CC genotype. This annotation only covers the pharmacokinetic relationship between rs28379954 and clozapine and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence serum concentrations of clozapine.	
1451356180	TT	There is currently no available evidence regarding the association between the rs28379954 TT genotype and clozapine concentrations. However, patients with schizophrenia and the CT genotype may have decreased serum concentrations of clozapine as compared to patients with the CC genotype. This annotation only covers the pharmacokinetic relationship between rs28379954 and clozapine and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence serum concentrations of clozapine.	
1451151506	CC	Patients with the CC genotype may be at a decreased risk of developing alcoholism as compared to patients with the CT or TT genotypes. Other genetic and clinical factors may also affect a patient's risk of developing alcoholism.	
1451151506	CT	Patients with the CT genotype may be at an increased risk of developing alcoholism as compared to patients with the CC genotype. Other genetic and clinical factors may also affect a patient's risk of developing alcoholism.	
1451151506	TT	Patients with the TT genotype may be at an increased risk of developing alcoholism as compared to patients with the CC genotype. Other genetic and clinical factors may also affect a patient's risk of developing alcoholism.	
1451356356	AA	Patients with opioid dependence and the rs11265549 AA genotype may be more likely to experience skin irritation when receiving methadone maintenance therapy (MMT) as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also influence the likelihood of experiencing kin irritation when receiving MMT.	
1451356356	AG	Patients with opioid dependence and the rs11265549 AG genotype may be less likely to experience skin irritation when receiving methadone maintenance therapy (MMT) as compared to patients with the AA genotype. Other genetic and clinical factors may also influence the likelihood of experiencing kin irritation when receiving MMT.	
1451356356	GG	Patients with opioid dependence and the rs11265549 GG genotype may be less likely to experience skin irritation when receiving methadone maintenance therapy (MMT) as compared to patients with the AA genotype. Other genetic and clinical factors may also influence the likelihood of experiencing kin irritation when receiving MMT.	
1451356386	AA	Patients with opioid dependence and the rs11265549 AA genotype may have decreased concentrations of methadone when receiving methadone maintenance therapy (MMT) as compared to patients with the AG or GG genotypes. This annotation only covers the pharmacokinetic relationship between rs11265549 and methadone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence methadone concetrations.	
1451356386	AG	Patients with opioid dependence and the rs11265549 AG genotype may have increased concentrations of methadone when receiving methadone maintenance therapy (MMT) as compared to patients with the AA genotype. This annotation only covers the pharmacokinetic relationship between rs11265549 and methadone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence methadone concetrations.	
1451356386	GG	Patients with opioid dependence and the rs11265549 GG genotype may have increased concentrations of methadone when receiving methadone maintenance therapy (MMT) as compared to patients with the AA genotype. This annotation only covers the pharmacokinetic relationship between rs11265549 and methadone and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence methadone concetrations.	
1451225320	AA	Infants who have been exposed to buprenorphine in utero and who are born to women with the rs4680 AA genotype may be more likely to require treatment with at least two medications for neonatal abstinence syndrome as compared to infants born to women with the AG or GG genotypes. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451225320	AG	Infants who have been exposed to buprenorphine in utero and who are born to women with the rs4680 AG genotype may be less likely to require treatment with at least two medications for neonatal abstinence syndrome as compared to infants born to women with the AA genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451225320	GG	Infants who have been exposed to buprenorphine in utero and who are born to women with the rs4680 GG genotype may be less likely to require treatment with at least two medications for neonatal abstinence syndrome as compared to infants born to women with the AA genotype. Be aware that this annotation is on the mother's genotype, even though the phenotype is observed in the infant and that this was not a statistically significant association. Other genetic and clinical factors may also affect severity of neonatal abstinence syndrome.	
1451356380	AA	Patients with opioid dependence and the rs11265549 AA genotype may require decreased doses of methadone when receiving methadone maintenance therapy (MMT) as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also influence methadone dosage requirements.	
1451356380	AG	Patients with opioid dependence and the rs11265549 AG genotype may require increased doses of methadone when receiving methadone maintenance therapy (MMT) as compared to patients with the AA genotype. Other genetic and clinical factors may also influence methadone dosage requirements.	
1451356380	GG	Patients with opioid dependence and the rs11265549 GG genotype may require increased doses of methadone when receiving methadone maintenance therapy (MMT) as compared to patients with the AA genotype. Other genetic and clinical factors may also influence methadone dosage requirements.	
1451240740	GG	Patients with bladder cancer and the GG genotype may be at an increased risk of developing neutropenia when treated with cisplatin as compared to patients with the TT genotype. Other genetic and clinical factors may also affect a patient's risk of developing neutropenia when treated with cisplatin.	
1451240740	GT	Patients with bladder cancer and the GT genotype may be at an increased risk of developing neutropenia when treated with cisplatin as compared to patients with the TT genotype. Other genetic and clinical factors may also affect a patient's risk of developing neutropenia when treated with cisplatin.	
1451240740	TT	Patients with bladder cancer and the TT genotype may be at a decreased risk of developing neutropenia when treated with cisplatin as compared to patients with the GG or GT genotypes. Other genetic and clinical factors may also affect a patient's risk of developing neutropenia when treated with cisplatin.	
1451240746	GG	Patients with bladder cancer and the GG genotype may be at an increased risk of experiencing drug toxicity when treated with cisplatin as compared to patients with the TT genotype. Other genetic and clinical factors may also affect a patient's risk of drug toxicity when treated with cisplatin.	
1451240746	GT	Patients with bladder cancer and the GT genotype may be at an increased risk of experiencing drug toxicity when treated with cisplatin as compared to patients with the TT genotype. Other genetic and clinical factors may also affect a patient's risk of drug toxicity when treated with cisplatin.	
1451240746	TT	Patients with bladder cancer and the TT genotype may be at a decreased risk of experiencing drug toxicity when treated with cisplatin as compared to patients with the GG or GT genotypes. Other genetic and clinical factors may also affect a patient's risk of drug toxicity when treated with cisplatin.	
1450815092	AA	Patients with schizophrenia and the AA genotype may have an increased response to risperidone as compared to patients with the AG or GG genotypes. Other genetic or clinical factors may also affect a patient's response to risperidone.	
1450815092	AG	Patients with schizophrenia and the AG genotype may have a decreased response to risperidone as compared to patients with the AA genotype but an increased response as compared to patients with the GG genotype. Other genetic or clinical factors may also affect a patient's response to risperidone.	
1450815092	GG	Patients with schizophrenia and the GG genotype may have a decreased response to risperidone as compared to patients with the AA or AG genotypes. Other genetic or clinical factors may also affect a patient's response to risperidone.	
1451240880	*15:02:01	Patients with one or two copies of the HLA-B*15:02:01 allele who are treated with dapsone may have an increased risk for dapsone-induced severe cutaneous adverse reactions as compared to patients with no HLA-B*15:02:01 alleles or negative for the HLA-B*15:02:01 test. Other genetic and clinical factors may also influence a patient's response to dapsone.	Presence
1451351160	AA	Patients with the rs1799971 AA genotype and chronic pain may experience increased quality of sleep when treated with opioids as compared to patients with the GG genotype. Other genetic and clinical factors may also influence sleep quality when treated with opioids.	
1451351160	AG	Patients with the rs1799971 AG genotype and chronic pain may experience increased quality of sleep when treated with opioids as compared to patients with the GG genotype. Other genetic and clinical factors may also influence sleep quality when treated with opioids.	
1451351160	GG	Patients with the rs1799971 GG genotype and chronic pain may experience decreased quality of sleep when treated with opioids as compared to patients with the AA or AG genotypes. Other genetic and clinical factors may also influence sleep quality when treated with opioids.	
1451277440	C	Patients with one X-chromosome and the C genotype who are treated with risperidone may have an increased risk of developing metabolic syndrome as compared to patients with the G genotype. Other genetic and clinical factors may also influence a patient's risk for developing metabolic syndrome.	
1451277440	CC	Patients with two X-chromosomes and the CC genotype who are treated with risperidone may have an increased risk of developing metabolic syndrome as compared to patients with the GG genotype. Other genetic and clinical factors may also influence a patient's risk for developing metabolic syndrome. This gene is on the X chromosome therefore some individuals may have only one allele.	
1451277440	CG	Patients with two X-chromosomes and the CG genotype who are treated with risperidone may have an increased risk of developing metabolic syndrome as compared to patients with the GG genotype. Other genetic and clinical factors may also influence a patient's risk for developing metabolic syndrome. This gene is on the X chromosome therefore some individuals may have only one allele.	
1451277440	G	Patients with one X-chromosome and the G genotype who are treated with risperidone may have a decreased risk of developing metabolic syndrome as compared to patients with the C genotype. This gene is on the X chromosome and males have only one allele. Other genetic and clinical factors may also influence a patient's risk for developing metabolic syndrome.	
1451277440	GG	Patients with two X-chromosomes and the GG genotype who are treated with risperidone may have a decreased, but not absent, risk of developing metabolic syndrome as compared to patients with the CG and CC genotype. Other genetic and clinical factors may also influence a patient's risk for developing metabolic syndrome. This gene is on the X chromosome therefore some individuals may have only one allele.	
1451244680	CC	Patients with the CC genotype may have increased concentrations of lovastatin acid as compared to patients with the TT genotype. Other genetic and clinical factors may also affect metabolism of lovastatin acid. This annotation only covers the pharmacokinetic relationship between rs4149056 and lovastatin acid and does not include evidence about clinical outcomes.	
1451244680	CT	Patients with the CT genotype may have increased concentrations of lovastatin acid as compared to patients with the TT genotype. Other genetic and clinical factors may also affect metabolism of lovastatin acid. This annotation only covers the pharmacokinetic relationship between rs4149056 and lovastatin acid and does not include evidence about clinical outcomes.	
1451244680	TT	Patients with the TT genotype may have decreased concentrations of lovastatin acid as compared to patients with the CC or CT genotypes. Other genetic and clinical factors may also affect metabolism of lovastatin acid. This annotation only covers the pharmacokinetic relationship between rs4149056 and lovastatin acid and does not include evidence about clinical outcomes.	
1451351240	CC	Patients with the rs79910351 CC genotype may have an increased response to fentanyl as compared to patients with the TT genotype. Other genetic and clinical factors may also affect response to fentanyl.	
1451351240	CT	There is currently no available evidence regarding the association between the rs79910351 CT genotype and response to fentanyl. However, patients with the rs79910351 TT genotype may have a decreased response to fentanyl as compared to patients with the CC genotype. Other genetic and clinical factors may also affect response to fentanyl.	
1451351240	TT	Patients with the rs79910351 TT genotype may have a decreased response to fentanyl as compared to patients with the CC genotype. Other genetic and clinical factors may also affect response to fentanyl.	
1451121880	AA	Patients with the AA genotype may have an increased risk for toxicity when treated with cisplatin chemotherapy regimens as compared to patients with the GG genotype. However, some studies find no association with drug toxicity. Other genetic and clinical factors may also influence a patient's response to platinum-based chemotherapy.	
1451121880	AG	Patients with the AG genotype may have an increased risk for toxicity when treated with cisplatin chemotherapy regimens as compared to patients with the GG genotype. However, some studies find no association with drug toxicity or one study reported reduced risk in heterozygotes. Other genetic and clinical factors may also influence a patient's response to platinum-based chemotherapy.	
1451121880	GG	Patients with the GG genotype may have a decreased risk for toxicity when treated with cisplatin chemotherapy regimens as compared to patients with the AA or AG genotype. However, some studies find no association with drug toxicity. Other genetic and clinical factors may also influence a patient's response to platinum-based chemotherapy.	
1451351260	CC	Patients with the rs79910351 CC genotype may have an increased response to remifentanil as compared to patients with the TT genotype. Other genetic and clinical factors may also affect response to remifentanil.	
1451351260	CT	There is currently no available evidence regarding the association between the rs79910351 CT genotype and response to remifentanil. However, patients with the rs79910351 TT genotype may have a decreased response to remifentanil as compared to patients with the CC genotype. Other genetic and clinical factors may also affect response to remifentanil.	
1451351260	TT	Patients with the rs79910351 TT genotype may have a decreased response to remifentanil as compared to patients with the CC genotype. Other genetic and clinical factors may also affect response to remifentanil.	
1451350801	*55:01:01	Patients with one or two copies of the HLA-B*55:01:01 allele may have an increased risk of hypersensitivity when treated with penicillin as compared to patients with no HLA-B*55:01:01 alleles or negative for the HLA-B*55:01:01 test. Other genetic and clinical factors may also influence risk of hypersensitivity to penicillin.	
1451350944	AA	Patients with the rs1799971 AA genotype may have increased severity of sleep apnea when treated with morphine as compared to patients with the AG genotype. Other genetic and clinical factors may also influence severity of sleep apnea when treated with morphine.	
1451350944	AG	Patients with the rs1799971 AG genotype may have decreased severity of sleep apnea when treated with morphine as compared to patients with the AA genotype. Other genetic and clinical factors may also influence severity of sleep apnea when treated with morphine.	
1451350944	GG	There is currently no available evidence regarding the association between the rs1799971 GG genotype and severity of sleep apnea when treated with morphine. However, patients with the rs1799971 AG genotype may have decreased severity of sleep apnea when treated with morphine as compared to patients with the AA genotype. Other genetic and clinical factors may also influence severity of sleep apnea when treated with morphine.	
1451325840	AA	There is currently no available evidence regarding the association between the rs671 AA genotype and acetaldehyde concentrations. However, patients with the rs671 AG genotype may have increased concentrations of acetaldehyde, a metabolite of ethanol, as compared to patients with the GG genotype. This annotation only covers the pharmacokinetic relationship between rs671 and acetaldehyde and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence concentrations of acetaldehyde.	
1451325840	AG	Patients with the rs671 AG genotype may have increased concentrations of acetaldehyde, a metabolite of ethanol, as compared to patients with the GG genotype. This annotation only covers the pharmacokinetic relationship between rs671 and acetaldehyde and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence concentrations of acetaldehyde.	
1451325840	GG	Patients with the rs671 GG genotype may have decreased concentrations of acetaldehyde, a metabolite of ethanol, as compared to patients with the AG genotype. This annotation only covers the pharmacokinetic relationship between rs671 and acetaldehyde and does not include evidence about clinical outcomes. Other genetic and clinical factors may also influence concentrations of acetaldehyde.	
1450375701	AA	Patients with the AA genotype may have a decreased response to allopurinol as compared to patients with the AC, CC or CT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.	
1450375701	AC	Patients with the AC genotype may have an increased response to allopurinol as compared to patients with the AA, AT or TT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.	
1450375701	AT	Patients with the AT genotype may have a decreased response to allopurinol as compared to patients with the AC, CC or CT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.	
1450375701	CC	Patients with the CC genotype may have an increased response to allopurinol as compared to patients with the AA, AT or TT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.	
1450375701	CT	Patients with the CT genotype may have an increased response to allopurinol as compared to patients with the AA, AT or TT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.	
1450375701	TT	Patients with the TT genotype may have a decreased response to allopurinol as compared to patients with the AC, CC or CT genotypes. Other genetic and clinical factors may also affect a patient's response to allopurinol.	
1451357200	CC	Patients with the rs4149056 CC genotype may have increased risk of statin-related myopathy or myalgia when treated with rosuvastatin as compared to patients with genotype TT. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect risk to rosuvastatin.	
1451357200	CT	Patients with the rs4149056 CT genotype may have increased risk of statin-related myopathy or myalgia when treated with rosuvastatin as compared to patients with genotype TT. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect risk to rosuvastatin.	
1451357200	TT	Patients with the rs4149056 TT genotype may have decreased risk of statin-related myopathy or myalgia when treated with rosuvastatin as compared to patients with genotype CT or CC. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect risk to rosuvastatin.	
1451244720	CC	Patients with the rs4149056 CC genotype may have an increased risk of developing myopathy when treated with fluvastatin as compared to patients with the TT genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect a patient's risk of developing fluvastatin-induced myopathy.	
1451244720	CT	Patients with the rs4149056 CT genotype may have an increased risk of developing myopathy when treated with fluvastatin as compared to patients with the TT genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect a patient's risk of developing fluvastatin-induced myopathy.	
1451244720	TT	Patients with the rs4149056 TT genotype may have a decreased risk of developing myopathy when treated with fluvastatin as compared to patients with the CC or CT genotypes. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect a patient's risk of developing fluvastatin-induced myopathy.	
1450810357	AA	Patients with the rs3778156 AA genotype may be at a decreased risk of developing cocaine dependence as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also affect a patient's risk of developing cocaine dependence.	
1450810357	AG	Patients with the rs3778156 AG genotype may be at an increased risk of developing cocaine dependence as compared to patients with the AA genotype. Other genetic and clinical factors may also affect a patient's risk of developing cocaine dependence.	
1450810357	GG	Patients with the rs3778156 GG genotype may be at an increased risk of developing cocaine dependence as compared to patients with the AA genotype. Other genetic and clinical factors may also affect a patient's risk of developing cocaine dependence.	
1451244700	CC	Patients with the rs4149056 CC genotype may have increased concentrations of fluvastatin as compared to patients with the TT genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect fluvastatin concentrations. This annotation only covers the pharmacokinetic relationship between rs4149056 and fluvastatin and does not include evidence about clinical outcomes.	
1451244700	CT	Patients with the rs4149056 CT genotype may have increased concentrations of fluvastatin as compared to patients with the TT genotype. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect fluvastatin concentrations. This annotation only covers the pharmacokinetic relationship between rs4149056 and fluvastatin and does not include evidence about clinical outcomes.	
1451244700	TT	Patients with the rs4149056 TT genotype may have decreased concentrations of fluvastatin as compared to patients with the CC or CT genotypes. However, conflicting evidence has been reported. Other genetic and clinical factors may also affect fluvastatin concentrations. This annotation only covers the pharmacokinetic relationship between rs4149056 and fluvastatin and does not include evidence about clinical outcomes.	
1451241320	*4	Patients with co-infection of HIV and tuberculosis and with at least one copy of the *4 allele may have a decreased risk of drug-induced liver injury when treated with a combination of HIV antivirals and anti-TB drugs as compared to patients with any combination of the *5, *6 or *7 alleles. Other genetic and clinical factors may also affect a patient's risk of drug-induced liver injury.	
1451241320	*5	Patients with co-infection of HIV and tuberculosis and with two copies of the *5 allele or one copy of the *5 allele in combination with the *6 or *7 alleles may have an increased risk of drug-induced liver injury when treated with a combination of HIV antivirals and anti-TB drugs as compared to patients with at least one copy of the *4, *12 or *13 alleles. Other genetic and clinical factors may also affect a patient's risk of drug-induced liver injury.	
1451241320	*6	Patients with co-infection of HIV and tuberculosis and with two copies of the *6 allele or one copy of the *6 allele in combination with the *5 or *7 alleles may have an increased risk of drug-induced liver injury when treated with a combination of HIV antivirals and anti-TB drugs as compared to patients with at least one copy of the *4, *12 or *13 alleles. Other genetic and clinical factors may also affect a patient's risk of drug-induced liver injury.	
1451241320	*7	Patients with co-infection of HIV and tuberculosis and with two copies of the *7 allele or one copy of the *7 allele in combination with the *5 or *6 alleles may have an increased risk of drug-induced liver injury when treated with a combination of HIV antivirals and anti-TB drugs as compared to patients with at least one copy of the *4, *12 or *13 alleles. Other genetic and clinical factors may also affect a patient's risk of drug-induced liver injury.	
1451241320	*12	Patients with co-infection of HIV and tuberculosis and with at least one copy of the *12 allele may have a decreased risk of drug-induced liver injury when treated with a combination of HIV antivirals and anti-TB drugs as compared to patients with any combination of the *5, *6 or *7 alleles. Other genetic and clinical factors may also affect a patient's risk of drug-induced liver injury.	
1451241320	*13	Patients with co-infection of HIV and tuberculosis and with at least one copy of the *13 allele may have a decreased risk of drug-induced liver injury when treated with a combination of HIV antivirals and anti-TB drugs as compared to patients with any combination of the *5, *6 or *7 alleles. Other genetic and clinical factors may also affect a patient's risk of drug-induced liver injury.	
1450375047	CC	Patients with testicular cancer and the CC genotype may have an increased risk of alopecia or pain as a result of treatment with bleomycin, cisplatin and etoposide as compared to patients with the CT or TT genotypes. Other genetic and clinical factors may also affect a patient's risk of alopecia or pain as a result of treatment with bleomycin, cisplatin and etoposide.	
1450375047	CT	Patients with testicular cancer and the CT genotype may have a decreased risk of alopecia or pain as a result of treatment with bleomycin, cisplatin and etoposide as compared to patients with the CC genotype. Other genetic and clinical factors may also affect a patient's risk of alopecia or pain as a result of treatment with bleomycin, cisplatin and etoposide.	
1450375047	TT	Patients with testicular cancer and the TT genotype may have a decreased risk of alopecia or pain as a result of treatment with bleomycin, cisplatin and etoposide as compared to patients with the CC genotype. Other genetic and clinical factors may also affect a patient's risk of alopecia or pain as a result of treatment with bleomycin, cisplatin and etoposide.	
1451357763	AA	Patients with breast cancer and the rs6990851 AA genotype may have a decreased response to anastrozole as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also influence response to anastrozole.	
'''
str = "1451357763	AA	Patients with breast cancer and the rs6990851 AA genotype may have a decreased response to anastrozole as compared to patients with the AG or GG genotypes. Other genetic and clinical factors may also influence response to anastrozole.	"

# for i in range(2860, 2880, 1):

#     print(str2[i])
#     print('\n')
#     print(i)
# data = np.array(['a','b','c','d'])
# s = pd.Series(data)
# print(s)
# print(tuple(s))

tpl = (981755803, 'rs75527207', 'CFTR', '1A', nan, 'Rare Variant; Tier 1 VIP', 234.875, 'Efficacy', 28, 30, '2021-03-24', 'https://www.pharmgkb.org/clinicalAnnotation/981755803', 'Pediatric', 'AA', 'Patients with the rs75527207 AA genotype (two copies of the CFTR G551D variant) and cystic fibrosis may respond to ivacaftor treatment. FDA-approved drug labeling information and CPIC guidelines indicate use of ivacaftor in cystic fibrosis patients with at least one copy of a list of 33 CFTR genetic variants, including G551D. Other genetic and clinical factors may also influence response to ivacaftor.', nan, 'PA166114461', 'Guideline Annotation', 'https://www.pharmgkb.org/guidelineAnnotation/PA166114461', nan, 'Annotation of CPIC Guideline for ivacaftor and CFTR', '100', nan, 3.0)

print(len(tpl))
