CREATE TABLE clingen_variants (
    ID  SERIAL PRIMARY KEY, 
    GENE_SYMBOL  TEXT, -- hgnc gene symbol
    HGNC_ID  VARCHAR(5), -- HGNC gen id
    DISEASE_LABEL TEXT,
    MONDO_DISEASE_ID VARCHAR(7),
    MOI VARCHAR(20), -- mode of inheritance 
    SOP VARCHAR(4),
    CLASSIFICATION VARCHAR(20),
    ONLINE_REPORT TEXT,
    CLASSIFICATION_DATE TIMESTAMPTZ,
    GCEP TEXT
);
