CREATE TABLE pharmgkb (
    ID SERIAL PRIMARY KEY,
    Clinical_Annotation_ID NUMERIC,
    VARIANT TEXT,
    GENE TEXT,
    LEVEL_OF_EVIDENCE TEXT,
    LEVEL_OVERRIDE TEXT,
    LEVEL_MODIFIERS TEXT,
    SCORE NUMERIC,
    PHENOTYPE_CATEGORY TEXT,
    PMID_COUNT NUMERIC,
    EVIDENCE_COUNT NUMERIC,
    DRU	Phenotype(s)	Latest History Date (YYYY-MM-DD)	URL	Specialty Population
);

CREATE TABLE DRUG (
    
);